# Generated by Django 2.0.2 on 2018-11-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=20)),
                ('MiddleName', models.CharField(blank=True, max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('Designation', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_id', models.AutoField(primary_key=True, serialize=False)),
                ('Emp', models.CharField(max_length=10)),
                ('Task_description', models.TextField(max_length=200)),
                ('Start_date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
    ]
