# Generated by Django 2.0.2 on 2018-11-25 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employeemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='addedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
